import { User, Task, AttendanceRecord, Project, Department, Notification, TimeEntry, Lead, Customer, Deal, SalesActivity } from '../types';

export const users: User[] = [
  {
    id: '1',
    name: 'John Smith',
    email: 'john.smith@ateliertechnologies.com',
    role: 'Super Admin',
    department: 'Management',
    isActive: true,
    createdAt: '2024-01-15',
  },
  {
    id: '2',
    name: 'Sarah Johnson',
    email: 'sarah.j@ateliertechnologies.com',
    role: 'Admin',
    department: 'HR',
    isActive: true,
    createdAt: '2024-02-10',
  },
  {
    id: '3',
    name: 'Michael Chen',
    email: 'michael.c@ateliertechnologies.com',
    role: 'Manager',
    department: 'Development',
    isActive: true,
    createdAt: '2024-01-20',
  },
  {
    id: '4',
    name: 'Emily Davis',
    email: 'emily.d@ateliertechnologies.com',
    role: 'Employee',
    department: 'Development',
    isActive: true,
    createdAt: '2024-03-05',
  },
  {
    id: '5',
    name: 'David Martinez',
    email: 'david.m@ateliertechnologies.com',
    role: 'Employee',
    department: 'Development',
    isActive: true,
    createdAt: '2024-03-12',
  },
  {
    id: '6',
    name: 'Lisa Anderson',
    email: 'lisa.a@ateliertechnologies.com',
    role: 'Manager',
    department: 'Design',
    isActive: true,
    createdAt: '2024-02-01',
  },
  {
    id: '7',
    name: 'Robert Wilson',
    email: 'robert.w@ateliertechnologies.com',
    role: 'Employee',
    department: 'Design',
    isActive: true,
    createdAt: '2024-03-20',
  },
  {
    id: '8',
    name: 'Jennifer Lee',
    email: 'jennifer.l@ateliertechnologies.com',
    role: 'Employee',
    department: 'Marketing',
    isActive: true,
    createdAt: '2024-04-01',
  },
  {
    id: '9',
    name: 'Tech Corp',
    email: 'contact@techcorp.com',
    role: 'Client',
    department: 'External',
    isActive: true,
    createdAt: '2024-02-15',
  },
  {
    id: '10',
    name: 'Alex Thompson',
    email: 'alex.t@ateliertechnologies.com',
    role: 'Manager',
    department: 'Sales',
    isActive: true,
    createdAt: '2024-01-25',
  },
  {
    id: '11',
    name: 'Rachel Martinez',
    email: 'rachel.m@ateliertechnologies.com',
    role: 'Employee',
    department: 'Sales',
    isActive: true,
    createdAt: '2024-03-15',
  },
  {
    id: '12',
    name: 'James Wilson',
    email: 'james.w@ateliertechnologies.com',
    role: 'Employee',
    department: 'Sales',
    isActive: true,
    createdAt: '2024-04-10',
  },
];

export const departments: Department[] = [
  { id: '1', name: 'Management', managerId: '1' },
  { id: '2', name: 'Development', managerId: '3' },
  { id: '3', name: 'Design', managerId: '6' },
  { id: '4', name: 'Marketing', managerId: '2' },
  { id: '5', name: 'HR', managerId: '2' },
  { id: '6', name: 'Sales', managerId: '10' },
];

export const projects: Project[] = [
  {
    id: '1',
    name: 'E-Commerce Platform',
    department: 'Development',
    status: 'Active',
    startDate: '2024-09-01',
  },
  {
    id: '2',
    name: 'Mobile App Redesign',
    department: 'Design',
    status: 'Active',
    startDate: '2024-10-15',
  },
  {
    id: '3',
    name: 'Marketing Campaign Q4',
    department: 'Marketing',
    status: 'Active',
    startDate: '2024-10-01',
  },
  {
    id: '4',
    name: 'Client Portal',
    department: 'Development',
    status: 'On Hold',
    startDate: '2024-08-01',
  },
  {
    id: '5',
    name: 'Brand Refresh',
    department: 'Design',
    status: 'Completed',
    startDate: '2024-06-01',
    endDate: '2024-09-30',
  },
];

export const tasks: Task[] = [
  {
    id: '1',
    title: 'Implement User Authentication',
    description: 'Set up secure authentication system with role-based access control',
    status: 'In Progress',
    priority: 'High',
    assignedTo: ['4', '5'],
    assignedBy: '3',
    createdAt: '2024-11-01',
    dueDate: '2024-11-15',
    project: 'E-Commerce Platform',
    department: 'Development',
    tags: ['backend', 'security'],
    timeSpent: 12,
    estimatedTime: 20,
    subtasks: [
      { id: '1-1', title: 'Design database schema', completed: true },
      { id: '1-2', title: 'Implement JWT tokens', completed: true },
      { id: '1-3', title: 'Add role-based middleware', completed: false },
      { id: '1-4', title: 'Write unit tests', completed: false },
    ],
    comments: [
      {
        id: 'c1',
        userId: '3',
        userName: 'Michael Chen',
        content: 'Great progress on this. Let\'s make sure we implement proper password hashing.',
        createdAt: '2024-11-05T10:30:00',
      },
      {
        id: 'c2',
        userId: '4',
        userName: 'Emily Davis',
        content: '@Michael Chen - Using bcrypt for password hashing. Will have this ready by Friday.',
        createdAt: '2024-11-05T14:15:00',
        mentions: ['3'],
      },
    ],
  },
  {
    id: '2',
    title: 'Design Landing Page Mockups',
    description: 'Create high-fidelity mockups for the new landing page',
    status: 'Completed',
    priority: 'Medium',
    assignedTo: ['7'],
    assignedBy: '6',
    createdAt: '2024-10-28',
    dueDate: '2024-11-08',
    project: 'E-Commerce Platform',
    department: 'Design',
    tags: ['design', 'ui/ux'],
    timeSpent: 16,
    estimatedTime: 16,
    subtasks: [
      { id: '2-1', title: 'Research competitor designs', completed: true },
      { id: '2-2', title: 'Create wireframes', completed: true },
      { id: '2-3', title: 'Design mockups', completed: true },
      { id: '2-4', title: 'Get client approval', completed: true },
    ],
  },
  {
    id: '3',
    title: 'Database Migration Script',
    description: 'Write migration scripts for the new database schema',
    status: 'To Do',
    priority: 'Urgent',
    assignedTo: ['5'],
    assignedBy: '3',
    createdAt: '2024-11-08',
    dueDate: '2024-11-12',
    project: 'E-Commerce Platform',
    department: 'Development',
    tags: ['backend', 'database'],
    timeSpent: 0,
    estimatedTime: 8,
  },
  {
    id: '4',
    title: 'Mobile App Navigation Flow',
    description: 'Define and design the navigation structure for the mobile app',
    status: 'In Progress',
    priority: 'High',
    assignedTo: ['7'],
    assignedBy: '6',
    createdAt: '2024-11-02',
    dueDate: '2024-11-14',
    project: 'Mobile App Redesign',
    department: 'Design',
    tags: ['mobile', 'ux'],
    timeSpent: 8,
    estimatedTime: 15,
  },
  {
    id: '5',
    title: 'Q4 Campaign Strategy Document',
    description: 'Prepare comprehensive strategy document for Q4 marketing campaign',
    status: 'Completed',
    priority: 'High',
    assignedTo: ['8'],
    assignedBy: '2',
    createdAt: '2024-10-20',
    dueDate: '2024-11-01',
    project: 'Marketing Campaign Q4',
    department: 'Marketing',
    tags: ['strategy', 'marketing'],
    timeSpent: 24,
    estimatedTime: 20,
  },
  {
    id: '6',
    title: 'API Documentation',
    description: 'Document all API endpoints with examples and usage guidelines',
    status: 'On Hold',
    priority: 'Low',
    assignedTo: ['4'],
    assignedBy: '3',
    createdAt: '2024-10-25',
    dueDate: '2024-11-20',
    project: 'E-Commerce Platform',
    department: 'Development',
    tags: ['documentation', 'backend'],
    timeSpent: 3,
    estimatedTime: 12,
  },
  {
    id: '7',
    title: 'Payment Gateway Integration',
    description: 'Integrate Stripe payment gateway for checkout process',
    status: 'To Do',
    priority: 'High',
    assignedTo: ['5'],
    assignedBy: '3',
    createdAt: '2024-11-09',
    dueDate: '2024-11-18',
    project: 'E-Commerce Platform',
    department: 'Development',
    tags: ['backend', 'payment'],
    timeSpent: 0,
    estimatedTime: 16,
  },
  {
    id: '8',
    title: 'Product Image Optimization',
    description: 'Optimize all product images for faster loading times',
    status: 'In Progress',
    priority: 'Medium',
    assignedTo: ['7'],
    assignedBy: '6',
    createdAt: '2024-11-07',
    dueDate: '2024-11-13',
    project: 'E-Commerce Platform',
    department: 'Design',
    tags: ['optimization', 'design'],
    timeSpent: 4,
    estimatedTime: 10,
  },
];

export const attendanceRecords: AttendanceRecord[] = [
  {
    id: 'a1',
    userId: '4',
    userName: 'Emily Davis',
    checkIn: '2024-11-11T09:00:00',
    checkOut: '2024-11-11T18:15:00',
    totalHours: 9.25,
    status: 'present',
    date: '2024-11-11',
  },
  {
    id: 'a2',
    userId: '5',
    userName: 'David Martinez',
    checkIn: '2024-11-11T09:15:00',
    checkOut: '2024-11-11T17:45:00',
    totalHours: 8.5,
    status: 'present',
    date: '2024-11-11',
  },
  {
    id: 'a3',
    userId: '7',
    userName: 'Robert Wilson',
    checkIn: '2024-11-11T08:45:00',
    checkOut: '2024-11-11T18:30:00',
    totalHours: 9.75,
    status: 'present',
    date: '2024-11-11',
  },
  {
    id: 'a4',
    userId: '8',
    userName: 'Jennifer Lee',
    checkIn: '2024-11-11T09:30:00',
    status: 'pending',
    date: '2024-11-11',
  },
  {
    id: 'a5',
    userId: '3',
    userName: 'Michael Chen',
    checkIn: '2024-11-11T08:30:00',
    checkOut: '2024-11-11T19:00:00',
    totalHours: 10.5,
    status: 'present',
    date: '2024-11-11',
  },
  {
    id: 'a6',
    userId: '6',
    userName: 'Lisa Anderson',
    checkIn: '2024-11-11T09:00:00',
    checkOut: '2024-11-11T17:30:00',
    totalHours: 8.5,
    status: 'present',
    date: '2024-11-11',
  },
];

export const notifications: Notification[] = [
  {
    id: 'n1',
    userId: '4',
    title: 'New Task Assigned',
    message: 'You have been assigned to "Implement User Authentication"',
    type: 'task',
    read: false,
    createdAt: '2024-11-11T09:30:00',
    link: '/tasks/1',
  },
  {
    id: 'n2',
    userId: '4',
    title: 'Mentioned in Comment',
    message: 'Michael Chen mentioned you in a comment',
    type: 'mention',
    read: false,
    createdAt: '2024-11-11T10:45:00',
    link: '/tasks/1',
  },
  {
    id: 'n3',
    userId: '5',
    title: 'Task Due Soon',
    message: 'Database Migration Script is due in 1 day',
    type: 'task',
    read: true,
    createdAt: '2024-11-11T08:00:00',
    link: '/tasks/3',
  },
  {
    id: 'n4',
    userId: '7',
    title: 'Check-in Reminder',
    message: 'Don\'t forget to check in for today',
    type: 'attendance',
    read: true,
    createdAt: '2024-11-11T08:30:00',
  },
];

export const timeEntries: TimeEntry[] = [
  {
    id: 't1',
    taskId: '1',
    userId: '4',
    startTime: '2024-11-11T09:30:00',
    endTime: '2024-11-11T12:30:00',
    duration: 3,
    notes: 'Worked on role-based middleware implementation',
  },
  {
    id: 't2',
    taskId: '1',
    userId: '5',
    startTime: '2024-11-11T10:00:00',
    endTime: '2024-11-11T13:00:00',
    duration: 3,
    notes: 'Implemented JWT token generation and validation',
  },
  {
    id: 't3',
    taskId: '4',
    userId: '7',
    startTime: '2024-11-11T14:00:00',
    endTime: '2024-11-11T17:00:00',
    duration: 3,
    notes: 'Created navigation flow wireframes',
  },
];

// CRM Mock Data
export const leads: Lead[] = [
  {
    id: 'l1',
    name: 'John Doe',
    company: 'TechStart Inc',
    email: 'john@techstart.com',
    phone: '+1-555-0101',
    source: 'Website',
    status: 'New',
    assignedTo: '11',
    assignedBy: '10',
    createdAt: '2024-11-10T10:00:00',
    tags: ['Enterprise', 'Software'],
    value: 50000,
    industry: 'Technology',
    region: 'North America',
  },
  {
    id: 'l2',
    name: 'Sarah Williams',
    company: 'Global Retail Co',
    email: 'sarah@globalretail.com',
    phone: '+1-555-0102',
    source: 'Referral',
    status: 'Contacted',
    assignedTo: '11',
    assignedBy: '10',
    createdAt: '2024-11-08T14:30:00',
    lastContactDate: '2024-11-11T09:00:00',
    tags: ['Retail', 'Mid-Market'],
    value: 75000,
    industry: 'Retail',
    region: 'North America',
    notes: 'Interested in our CRM solution. Follow up next week.',
  },
  {
    id: 'l3',
    name: 'Michael Brown',
    company: 'Finance Solutions Ltd',
    email: 'mbrown@financesolutions.com',
    phone: '+1-555-0103',
    source: 'Cold Call',
    status: 'Qualified',
    assignedTo: '12',
    assignedBy: '10',
    createdAt: '2024-11-05T11:15:00',
    lastContactDate: '2024-11-10T15:30:00',
    tags: ['Finance', 'Enterprise'],
    value: 120000,
    industry: 'Finance',
    region: 'Europe',
  },
  {
    id: 'l4',
    name: 'Emily Chen',
    company: 'HealthCare Plus',
    email: 'echen@healthcareplus.com',
    phone: '+1-555-0104',
    source: 'Email Campaign',
    status: 'Proposal',
    assignedTo: '11',
    assignedBy: '10',
    createdAt: '2024-11-01T09:00:00',
    lastContactDate: '2024-11-11T14:00:00',
    tags: ['Healthcare', 'Enterprise'],
    value: 95000,
    industry: 'Healthcare',
    region: 'North America',
  },
  {
    id: 'l5',
    name: 'David Kumar',
    company: 'EduTech Academy',
    email: 'dkumar@edutech.com',
    phone: '+1-555-0105',
    source: 'Social Media',
    status: 'Won',
    assignedTo: '12',
    assignedBy: '10',
    createdAt: '2024-10-20T10:30:00',
    lastContactDate: '2024-11-05T11:00:00',
    tags: ['Education', 'Small Business'],
    value: 35000,
    industry: 'Education',
    region: 'Asia',
  },
  {
    id: 'l6',
    name: 'Lisa Anderson',
    company: 'Manufacturing Corp',
    email: 'landerson@mfgcorp.com',
    phone: '+1-555-0106',
    source: 'Trade Show',
    status: 'Lost',
    assignedTo: '11',
    assignedBy: '10',
    createdAt: '2024-10-15T13:00:00',
    lastContactDate: '2024-10-28T10:00:00',
    tags: ['Manufacturing'],
    value: 80000,
    industry: 'Manufacturing',
    region: 'North America',
    notes: 'Chose competitor. Price was the main factor.',
  },
];

export const customers: Customer[] = [
  {
    id: 'c1',
    name: 'David Kumar',
    company: 'EduTech Academy',
    email: 'dkumar@edutech.com',
    phone: '+1-555-0105',
    address: '123 Education St, San Francisco, CA 94105',
    industry: 'Education',
    region: 'Asia',
    assignedTo: '12',
    createdAt: '2024-11-05T11:00:00',
    totalValue: 35000,
    lastContactDate: '2024-11-10T14:30:00',
    tags: ['Active', 'Small Business'],
    status: 'Active',
    notes: [
      {
        id: 'cn1',
        userId: '12',
        userName: 'James Wilson',
        content: 'Initial contract signed. Very happy with the platform.',
        createdAt: '2024-11-05T11:30:00',
        type: 'note',
      },
      {
        id: 'cn2',
        userId: '12',
        userName: 'James Wilson',
        content: 'Follow-up call scheduled for product training.',
        createdAt: '2024-11-08T10:00:00',
        type: 'call',
      },
    ],
  },
  {
    id: 'c2',
    name: 'Robert Martinez',
    company: 'Global Solutions Inc',
    email: 'rmartinez@globalsolutions.com',
    phone: '+1-555-0201',
    address: '456 Business Ave, New York, NY 10001',
    industry: 'Consulting',
    region: 'North America',
    assignedTo: '11',
    createdAt: '2024-09-15T09:00:00',
    totalValue: 145000,
    lastContactDate: '2024-11-09T16:00:00',
    tags: ['VIP', 'Enterprise'],
    status: 'VIP',
    notes: [
      {
        id: 'cn3',
        userId: '11',
        userName: 'Rachel Martinez',
        content: 'Discussing expansion to additional departments.',
        createdAt: '2024-11-09T16:00:00',
        type: 'meeting',
      },
    ],
  },
  {
    id: 'c3',
    name: 'Amanda Foster',
    company: 'Tech Innovations LLC',
    email: 'afoster@techinnovations.com',
    phone: '+1-555-0202',
    industry: 'Technology',
    region: 'North America',
    assignedTo: '11',
    createdAt: '2024-08-20T14:30:00',
    totalValue: 89000,
    lastContactDate: '2024-11-11T11:00:00',
    tags: ['Active', 'Mid-Market'],
    status: 'Active',
    notes: [],
  },
];

export const deals: Deal[] = [
  {
    id: 'd1',
    title: 'TechStart Inc - CRM Implementation',
    customerId: 'l1',
    customerName: 'TechStart Inc',
    amount: 50000,
    expectedCloseDate: '2024-12-15',
    stage: 'Qualification',
    probability: 40,
    assignedTo: '11',
    createdAt: '2024-11-10T10:00:00',
    updatedAt: '2024-11-11T15:00:00',
    product: 'CRM Software',
    campaign: 'Q4 Enterprise Campaign',
    tags: ['Enterprise', 'Software'],
  },
  {
    id: 'd2',
    title: 'Global Retail Co - Task Management System',
    customerId: 'l2',
    customerName: 'Global Retail Co',
    amount: 75000,
    expectedCloseDate: '2024-12-01',
    stage: 'Proposal',
    probability: 60,
    assignedTo: '11',
    createdAt: '2024-11-08T14:30:00',
    updatedAt: '2024-11-11T10:00:00',
    product: 'Task Management',
    tags: ['Retail', 'Mid-Market'],
    notes: 'Proposal sent on Nov 10. Awaiting response.',
  },
  {
    id: 'd3',
    title: 'Finance Solutions Ltd - Full Suite',
    customerId: 'l3',
    customerName: 'Finance Solutions Ltd',
    amount: 120000,
    expectedCloseDate: '2024-11-25',
    stage: 'Negotiation',
    probability: 75,
    assignedTo: '12',
    createdAt: '2024-11-05T11:15:00',
    updatedAt: '2024-11-11T16:30:00',
    product: 'Complete Platform',
    campaign: 'Enterprise Solutions',
    tags: ['Finance', 'Enterprise'],
  },
  {
    id: 'd4',
    title: 'HealthCare Plus - CRM + Attendance',
    customerId: 'l4',
    customerName: 'HealthCare Plus',
    amount: 95000,
    expectedCloseDate: '2024-11-30',
    stage: 'Proposal',
    probability: 65,
    assignedTo: '11',
    createdAt: '2024-11-01T09:00:00',
    updatedAt: '2024-11-11T14:00:00',
    product: 'CRM + Attendance Module',
    tags: ['Healthcare', 'Enterprise'],
  },
  {
    id: 'd5',
    title: 'Global Solutions - Department Expansion',
    customerId: 'c2',
    customerName: 'Global Solutions Inc',
    amount: 65000,
    expectedCloseDate: '2024-12-20',
    stage: 'Prospecting',
    probability: 30,
    assignedTo: '11',
    createdAt: '2024-11-09T16:00:00',
    updatedAt: '2024-11-10T09:00:00',
    product: 'Additional Licenses',
    tags: ['Upsell', 'VIP'],
  },
];

export const salesActivities: SalesActivity[] = [
  {
    id: 'sa1',
    userId: '11',
    userName: 'Rachel Martinez',
    type: 'call',
    leadId: 'l2',
    date: '2024-11-11T09:00:00',
    duration: 30,
    notes: 'Discussed pricing and implementation timeline. Customer very interested.',
    outcome: 'Positive - Moving to proposal stage',
  },
  {
    id: 'sa2',
    userId: '12',
    userName: 'James Wilson',
    type: 'meeting',
    customerId: 'c1',
    date: '2024-11-10T14:30:00',
    duration: 60,
    notes: 'Product training session. Customer satisfied with features.',
    outcome: 'Completed - Follow up in 2 weeks',
  },
  {
    id: 'sa3',
    userId: '11',
    userName: 'Rachel Martinez',
    type: 'email',
    dealId: 'd2',
    date: '2024-11-10T16:00:00',
    notes: 'Sent detailed proposal with pricing breakdown and implementation plan.',
    outcome: 'Awaiting response',
  },
  {
    id: 'sa4',
    userId: '12',
    userName: 'James Wilson',
    type: 'demo',
    leadId: 'l3',
    date: '2024-11-10T15:30:00',
    duration: 45,
    notes: 'Product demo for Finance Solutions. Showed reporting and analytics features.',
    outcome: 'Very positive - Entering negotiation',
  },
];
